import {
  AddressSchema,
  AgeSchema,
  AnnotationSchema,
  AttachmentSchema,
  CodeableConceptSchema,
  CodingSchema,
  ContactDetailSchema,
  ContactPointSchema,
  ContributorSchema,
  CountSchema,
  DataRequirementSchema,
  DistanceSchema,
  DosageSchema,
  DurationSchema,
  ExpressionSchema,
  ExtensionSchema,
  HumanNameSchema,
  IdentifierSchema,
  MetaSchema,
  MoneySchema,
  ParameterDefinitionSchema,
  PeriodSchema,
  PrimitiveBase64BinarySchema,
  PrimitiveBooleanSchema,
  PrimitiveCanonicalSchema,
  PrimitiveCodeSchema,
  PrimitiveDateSchema,
  PrimitiveDateTimeSchema,
  PrimitiveDecimalSchema,
  PrimitiveIdSchema,
  PrimitiveInstantSchema,
  PrimitiveIntegerSchema,
  PrimitiveMarkdownSchema,
  PrimitiveOidSchema,
  PrimitivePositiveIntSchema,
  PrimitiveStringSchema,
  PrimitiveTimeSchema,
  PrimitiveUnsignedIntSchema,
  PrimitiveUriSchema,
  PrimitiveUrlSchema,
  PrimitiveUuidSchema,
  QuantitySchema,
  RangeSchema,
  RatioSchema,
  ReferenceSchema,
  RelatedArtifactSchema,
  SampledDataSchema,
  SignatureSchema,
  TimingSchema,
  TriggerDefinitionSchema,
  UsageContextSchema,
} from './headers';

ExtensionSchema.add({
  url: PrimitiveUriSchema,
  _valueBase64Binary: PrimitiveBase64BinarySchema,
  _valueBoolean: PrimitiveBooleanSchema,
  _valueCanonical: PrimitiveCanonicalSchema,
  _valueCode: PrimitiveCodeSchema,
  _valueDate: PrimitiveDateSchema,
  _valueDateTime: PrimitiveDateTimeSchema,
  _valueDecimal: PrimitiveDecimalSchema,
  _valueId: PrimitiveIdSchema,
  _valueInstant: PrimitiveInstantSchema,
  _valueInteger: PrimitiveIntegerSchema,
  _valueMarkdown: PrimitiveMarkdownSchema,
  _valueOid: PrimitiveOidSchema,
  _valuePositiveInt: PrimitivePositiveIntSchema,
  _valueString: PrimitiveStringSchema,
  _valueTime: PrimitiveTimeSchema,
  _valueUnsignedInt: PrimitiveUnsignedIntSchema,
  _valueUri: PrimitiveUriSchema,
  _valueUrl: PrimitiveUrlSchema,
  _valueUuid: PrimitiveUuidSchema,
  _valueAddress: AddressSchema,
  _valueAge: AgeSchema,
  _valueAnnotation: AnnotationSchema,
  _valueAttachment: AttachmentSchema,
  _valueCodeableConcept: CodeableConceptSchema,
  _valueCoding: CodingSchema,
  _valueContactPoint: ContactPointSchema,
  _valueCount: CountSchema,
  _valueDistance: DistanceSchema,
  _valueDuration: DurationSchema,
  _valueHumanName: HumanNameSchema,
  _valueIdentifier: IdentifierSchema,
  _valueMoney: MoneySchema,
  _valuePeriod: PeriodSchema,
  _valueQuantity: QuantitySchema,
  _valueRange: RangeSchema,
  _valueRatio: RatioSchema,
  _valueReference: ReferenceSchema,
  _valueSampledData: SampledDataSchema,
  _valueSignature: SignatureSchema,
  _valueTiming: TimingSchema,
  _valueContactDetail: ContactDetailSchema,
  _valueContributor: ContributorSchema,
  _valueDataRequirement: DataRequirementSchema,
  _valueExpression: ExpressionSchema,
  _valueParameterDefinition: ParameterDefinitionSchema,
  _valueRelatedArtifact: RelatedArtifactSchema,
  _valueTriggerDefinition: TriggerDefinitionSchema,
  _valueUsageContext: UsageContextSchema,
  _valueDosage: DosageSchema,
  _valueMeta: MetaSchema,
  id: String,
  extension: [ExtensionSchema],
});

export default ExtensionSchema;
